name: Deploy RAG News Chatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Test environment setup
      run: npm run test:env
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
    
    - name: Build application
      run: npm run build
    
    - name: Run system tests
      run: npm run test:system
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
        TEST_URL: http://localhost:3000

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup news data
      run: npm run deploy:setup
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
